# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-24 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_event_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invites',
            field=models.CharField(default='admin', max_length=2000),
        ),
    ]
