# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_event_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invites',
            field=models.CharField(choices=[['admin', 'Administrator'], ['vis', 'Vishal'], ['vais', 'Vaisakh']], default='admin', max_length=2000),
        ),
    ]
